### ISSUE TITLE
License in package.json does not match that in the repo.

### ISSUE THREAD

**Issue by willstott101** [matt-gadd/umd-compat-loader#6]
Would you be willing to update the package.json license entry to `"Apache-2.0"` so that it matches the source repo? It's a little confusing currently, especially as I think "BSD" might be ambiguous.

Thanks for your work here!

**Comment by matt-gadd** [comment]
sorry i didn't see this issue 😞, yup i'll update the package.json thanks for the heads up!

**Comment by matt-gadd** [comment]
@willstott101 i've updated the package.json and published 2.1.2 with the corrected license. thanks!
